package edu.csus.csc131.euc;
import edu.csus.csc131.euc.model.*;

/**
 *
 * @author htetm
 */
public class MainWindow extends javax.swing.JPanel {

    /**
     * Creates new form MainWindow
     */
    private static final long serialVersionUID = 4L;

    public MainWindow() {
        initComponents();
    }

    public void addProfile(Profile profile) {
        this.profile = profile;
    }

    public Profile getProfile(){
        return profile;
    }

    public void updateTimeSlotField(){
        String s;
        s = currentIndex + ":00 to " + (currentIndex+1) + ":00";
        timeSlotTextField.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usageLabel = new javax.swing.JLabel();
        usageTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        timeSlotSlider = new javax.swing.JSlider();
        timeSlotLabel = new javax.swing.JLabel();
        timeSlotTextField = new javax.swing.JTextField();
        runningCostLabel = new javax.swing.JLabel();
        runningCostTextField = new javax.swing.JTextField();
        importJSONButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 344));

        usageLabel.setText("Usage:");

        usageTextField.setEditable(true);
        usageTextField.setBackground(new java.awt.Color(255, 255, 255));
        usageTextField.setText("");
        usageTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usageTextFieldActionPerformed(evt);
            }
        });

        timeSlotSlider.setBackground(new java.awt.Color(255, 255, 255));
        timeSlotSlider.setMaximum(24);
        timeSlotSlider.setMinimum(1);
        timeSlotSlider.setMinorTickSpacing(1);
        timeSlotSlider.setSnapToTicks(true);

        timeSlotLabel.setBackground(new java.awt.Color(0, 0, 0));
        timeSlotLabel.setText("Timeslot: ");

        timeSlotTextField.setEditable(false);
        timeSlotTextField.setBackground(new java.awt.Color(255, 255, 255));
        timeSlotTextField.setText("");
        updateTimeSlotField();
        timeSlotTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        timeSlotTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotTextFieldActionPerformed(evt);
            }
        });

        runningCostLabel.setBackground(new java.awt.Color(255, 255, 255));
        runningCostLabel.setText("Running Cost:");

        runningCostTextField.setText("0.00");
        runningCostTextField.setEditable(false);
        runningCostTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        runningCostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runningCostTextFieldActionPerformed(evt);
            }
        });

        importJSONButton.setBackground(new java.awt.Color(51, 153, 255));
        importJSONButton.setText("Import JSON");
        importJSONButton.setBorder(null);
        importJSONButton.setBorderPainted(false);
        importJSONButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importJSONButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importJSONButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(timeSlotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(timeSlotTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(runningCostLabel)
                                .addComponent(usageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(usageTextField)
                                .addComponent(runningCostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addComponent(timeSlotSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(importJSONButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeSlotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeSlotTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSlotSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runningCostLabel)
                    .addComponent(runningCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>

    private void usageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {

        //store value and clear the textfield
        profile.getUsage().setUsage(Integer.parseInt(usageTextField.getText()), currentIndex);
        timeSlotTextField.setText("");

        //nextTimeSlot, loops back after 23
        currentIndex++;
        currentIndex = currentIndex % 24;
        updateTimeSlotField();

        //compute running cost and update field
        runningCostTextField.setText(String.format("%.2f", profile.calculate()));
    }

    private void timeSlotTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        //nothing
    }

    private void runningCostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        //nothing
    }

    private void importJSONButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //import JSON yet to be implemented
    }


    // Variables declaration - do not modify
    private javax.swing.JButton importJSONButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel runningCostLabel;
    private javax.swing.JTextField runningCostTextField;
    private javax.swing.JLabel timeSlotLabel;
    private javax.swing.JSlider timeSlotSlider;
    private javax.swing.JTextField timeSlotTextField;
    private javax.swing.JLabel usageLabel;
    private javax.swing.JTextField usageTextField;

    private int currentIndex;
    private Profile profile;
    // End of variables declaration
}
